---
- name: Remove Paperless
  tags:
    - reset
    - remove
    - remove_paperless
  block:
    - name: Stop containers if running
      ansible.builtin.shell: |
        docker inspect -f '{{ "{{.State.Running}}" }}' "{{ item.container_name }}" | grep true >/dev/null 2>&1 && \
        docker stop "{{ item.container_name }}" || true
      args:
        executable: /bin/bash
      loop: "{{ paperless }}"
      loop_control:
        label: "{{ item.container_name }}"
      changed_when: true
      tags: skip_ansible_lint

    - name: Remove containers if exist
      ansible.builtin.shell: |
        docker ps -a --format '{{ "{{.Names}}" }}' | grep -w "{{ item.container_name }}" >/dev/null 2>&1 && \
        docker rm "{{ item.container_name }}" || true
      args:
        executable: /bin/bash
      loop: "{{ paperless }}"
      loop_control:
        label: "{{ item.container_name }}"
      changed_when: true
      tags: skip_ansible_lint
